Repository googleapis/nodejs-memcache, pull requests merged in 2020-07, with the labels that each got.

#33 docs: Change relative URLs to absolute URLs to fix broken links.
  protos/google/cloud/memcache/v1beta2/cloud_memcache.proto
  synth.metadata
Labels: cla: yes, context: full

#38 build: use bazel build
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#39 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#41 build: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#43 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#45 build: fix typo in publish script
  .kokoro/publish.sh
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: partial

#46 chore: add config files for cloud-rad for node.js
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#47 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#48 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#49 chore: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#50 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#51 build: update protos
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none
