Repository googleapis/nodejs-memcache, pull requests merged in 2020-05, with the labels that each got.

#23 feat: check status of long running operation by its name
  protos/protos.js
  src/v1beta2/cloud_memcache_client.ts
  synth.metadata
  test/gapic_cloud_memcache_v1beta2.ts
Labels: automerge, cla: yes

#25 chore: linting rules
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none

#26 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
